### ISSUE TITLE
add agent type to configuration file

### ISSUE THREAD

**Issue by TimoGlastra** [animo/agent-cli#119]
If we add more agent types (such as AFJ) in the future it will be useful to have an agent type per environment. E.g. something like:

```yaml
configurations:
  default:
    type: acapy
    endpoint: "https://agent.ssi.community"
    api_key: ~
    auth_token: ~
```

Maybe even add a version if that is going to help, but not sure it is needed
